### ISSUE TITLE
Upgrade to the latest version of drf_yasg

### ISSUE THREAD

**Issue by nishantwrp** [COPS-IITBHU/hackalog-backend#2]
Upgrade to the latest version of drf_yasg once the following issue is fixed.
https://github.com/axnsan12/drf-yasg/issues/641

**Comment by krashish8** [comment]
@nishantwrp As mentioned in that issue, the maintainers of that repo are not replying, so I think we should now switch to the fork of drf-yasg - [drf-yasg2](https://github.com/JoelLefkowitz/drf-yasg). The compatible and stable version of that package is now available on pypi; drf-yasg2
