### ISSUE TITLE
GET ​/hackathons​/{id}​/submissions​/ - Team does not exist!

### ISSUE THREAD

**Issue by shubhanshu02** [COPS-IITBHU/hackalog-backend#20]
## Description
In case the user is not logged in and uses this API for an ongoing hackathon, it shows that the team doesn't exist. Instead, it should show an empty array since the hackathon is ongoing, and no submissions should be displayed for now (except the user's team's submission in case the user is logged in).

Expected Output: `[]`

## Steps to Reproduce
1. Open this [link](https://cops-hackalog.herokuapp.com/).
2. Try out `GET ​/hackathons​/{id}​/submissions​/` with hackathon id = 2 (Ongoing Hackathon)
3. The output is `{  "detail": "Team does not exist!"}`

**Comment by m-e-l-u-h-a-n** [comment]
Closed by #24 !
